export const pokemonColorThemes = {
  red: {
    bg: "pink-200",
    text: "black-900-text",
    border: "stroke-pink-600",
    accent: "stroke-pink-400",
    header: "pink-800",
  },
  blue: {
    bg: "cyan-200",
    text: "black-900-text",
    border: "stroke-cyan-600",
    accent: "stroke-cyan-400",
    header: "cyan-800",
  },
  yellow: {
    bg: "orange-200",
    text: "black-900-text",
    border: "stroke-orange-600",
    accent: "stroke-orange-400",
    header: "orange-800",
  },
  green: {
    bg: "yellow-green-200",
    text: "black-900-text",
    border: "stroke-yellow-green-600",
    accent: "stroke-yellow-green-400",
    header: "yellow-green-800",
  },
  black: {
    bg: "blacka-200",
    text: "black-900-text",
    border: "stroke-blacka-600",
    accent: "stroke-blacka-400",
    header: "blacka-800",
  },
  brown: {
    bg: "red-200",
    text: "black-900-text",
    border: "stroke-red-600",
    accent: "stroke-red-400",
    header: "red-800",
  },
  purple: {
    bg: "periwinkle-200",
    text: "black-900-text",
    border: "stroke-periwinkle-600",
    accent: "stroke-periwinkle-400",
    header: "periwinkle-800",
  },
  gray: {
    bg: "gray-200",
    text: "black-900-text",
    border: "stroke-gray-600",
    accent: "stroke-gray-400",
    header: "gray-800",
  },
  white: {
    bg: "whitea-200",
    text: "black-900-text",
    border: "stroke-whitea-600",
    accent: "stroke-whitea-400",
    header: "whitea-800",
  },
  pink: {
    bg: "magenta-200",
    text: "black-900-text",
    border: "stroke-magenta-600",
    accent: "stroke-magenta-400",
    header: "magenta-800",
  },
  default: {
    bg: "black-transparent-700",
    text: "white-100-text",
    border: "stroke-default-700 ",
    accent: "stroke-default-700 ",
    header: "black-800",
  },
};
